name: news_app
description: News App

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.0
  dio: ^4.0.4
  get: ^4.6.1
  get_storage: ^2.0.3
  intl: ^0.17.0
  multi_select_flutter: ^4.0.0
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaNeue.otf
